ext.cpp=.cpp
ext.go=.go
ext.asm=.asm

# Linux toolchain (Replit)
build.cpp.linux=g++ -std=c++20 -O2 -march=x86-64 -c "{in}" -o "{out}"
build.go.linux=go build -buildmode=c-shared -o {outdir}/{name}.so {in}
build.asm.linux=nasm -f elf64 "{in}" -o "{out}" -Worphan-labels
linker.linux=g++ -O2 -march=x86-64 -o "{out}" {objs} -ldl -pthread
